src/glosuj_lokalnie/views.py
# coding=utf-8
# Created 2014 by Janusz Skonieczny
import json
import logging

from werkzeug.utils import redirect
from flask import request, render_template, make_response, url_for
from flask.blueprints import Blueprint
from flask_multi_view import actions
from flask_multi_view.actions import BaseActionView
from flask_multi_view.extensions.sqlachemy import ModelView, ModelRPC

from website.database import db
from .models import Application
from .pdfutils import BasePdfRendering

app = Blueprint("glosuj_lokalnie", __name__, template_folder="templates")
COOKIE_NAME = 'wniosek2'


@actions.routes(app)
class ApplicationView(ModelView):
    model = Application

    # @actions.route("create", methods=['GET'])
    def create(self, *args, **kwargs):
        data = request.cookies.get(COOKIE_NAME)
        obj = Application.from_json(data) if data else None
        form = self._get_form("create", obj=obj)
        next_url = request.args.get("next_url")
        if not form.validate_on_submit():
            # not valid show the form again
            return self._render("create", form=form, next_url=next_url)

        self.obj = form.save()
        rv = redirect(url_for(".Application:pdf"))
        data = json.dumps(self.obj, default=lambda o: o.json())
        rv.set_cookie(COOKIE_NAME, data)
        return rv

    @actions.route("pdf", methods=['GET'])
    def pdf(self, **kwargs):
        data = request.cookies.get(COOKIE_NAME)
        if data:
            data = json.loads(data)
            logging.debug("data: %s" % data)
            if not data:
                return redirect(url_for('.Application:create'))
        application = Application()
        logging.debug("application: %s" % application)
        application.populate(**data)
        from StringIO import StringIO
        output = StringIO()
        application.pdf(output)
        output = output.getvalue()
        rv = make_response(output)
        rv.headers['Content-Type'] = 'application/pdf'
        name = 'Wniosek-o-wpisanie-do-rejestru-wyborcow'
        rv.headers['Content-Disposition'] = 'inline; filename=%s.pdf' % name
        return rv

    def pdf2(self, **kwargs):
        data = request.cookies.get(COOKIE_NAME)
        data = json.loads(data)
        logging.debug("data: %s" % data)
        if not data:
            return redirect(url_for('.Application:create'))

        from xhtml2pdf import pisa
        from StringIO import StringIO
        html = render_template('Application/pdf.html', object=data)
        logging.debug("html: %s" % html)
        rv = StringIO()
        pdf = pisa.CreatePDF(StringIO(html.encode('utf-8')), rv)
        logging.debug("pdf.err: %s" % pdf.err)
        logging.debug("pdf: %s" % pdf)
        rv = make_response(rv.getvalue())
        rv.headers['Content-Type'] = 'application/pdf'
        name = 'Wniosek o wpisanie do rejestru wyborcow'
        rv.headers['Content-Disposition'] = 'inline; filename=%s.pdf' % name

        return rv

@app.route("/polityka-prywatnosci")
def polityka():
    return render_template("polityka.html")


@app.route('/sitemap.xml')
def sitemap():
    return render_template("sitemap2.xml")

templates/_body_cms.html
{% load staticfiles compress cms_tags sekizai_tags menu_tags %}
{% block page_title %}{% page_attribute page_title %}{% endblock %}

{% block head %}
    <title>{% block page_title %}{% page_attribute page_title %}{% endblock %}</title>
    <meta name="description" content="{% page_attribute meta_description %}">
    <meta name="keywords" content="{% page_attribute meta_keywords %}"/>
    <meta name="viewport" content="width=device-width">

    {% if LANGUAGE_CODE == 'pl' %}
        <link rel="alternate" hreflang="en" href="{% page_language_url "en" %}"/>
    {% else %}
        <link rel="alternate" hreflang="pl" href="{% page_language_url "pl" %}"/>
    {% endif %}

    {% block css %}{% endblock %}{% block js %}{% endblock %}{% render_block "css" %}

    {% with base_url="http://budzet.lomianki.org" %}

        <link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap.xml"/>
        <link rel="home" href="{{ base_url }}"/>
        {% if request.current_page %}
            <link rel="canonical" href="{{ base_url }}{% page_url request.current_page %}"/>
        {% endif %}
        <link rel="author" href="/static/humans.txt"/>
        <link rel="publisher" href="https://plus.google.com/+JanuszSkonieczny/"/>

        <meta name="geo.placename" content="Łomianki, Mazowieckie, Polska"/>
        <meta name="geo.position" content="52.331622,20.893501"/>
        <meta name="geo.region" content="Warszawa"/>
        <meta name="ICBM" content="52.334849, 20.887077"/>
        <meta name="DC.title" content="{% page_attribute page_title %}">

        <!-- TODO: poprawić FB -->
        <meta name="og:street" content=""/>
        <meta name="og:phone_number" content=""/>
        <meta name="og:locality" content="Łomianki"/>
        <meta name="og:region" content="MAZ"/>

        <meta name="og:type" content="website"/>
        {% if request.current_page %}
            <meta name="og:url" content="{{ base_url }}{% page_url request.current_page %}"/>
        {% endif %}
        <meta name="og:image" content="{{ base_url }}{% static 'fb-logo.png' %}"/>
        <meta name="og:site_name" content="Budżet Obywatelski Łomianek"/>
        <meta name="fb:admins" content="185398204820326&"/>
        <meta name="og:description" content="{% page_attribute meta_description %}"/>
        <meta name="google-site-verification" content=""/>

    {% endwith %}
{% endblock %}
{% block body %}
    {% cms_toolbar %}
{% endblock %}

templates/base.html
{% extends "body.html" %}
{% block body %}
    <div id="root">
        {% include "header_nav.html" %}
        <section id="content">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        {% include "bootstrap/alerts.html" %}
                    </div>
                </div>
            </div>
            <section class="main">
                <div class="main-inner">
                    {% block main %}{% endblock %}
                </div>
            </section>
        </section>
        <div id="footer-shim"></div>
    </div>
    <div class="clearfix visible-xs-block"></div>
    {% include "footer.html" %}
{% endblock %}

templates/body.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    {% assets "css" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Bitter&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <link rel="home" href="/"/>

    <meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8"/>
    <meta name="description" content="Możesz zagłosować w Łomiankach bez meldunku. Wypełnij nasz formularz i dopisz się do rejestru wyborców."/>
    <meta name="keywords" content="wybory 2014, łomianki, dialog łomianki, witold gawda"/>
    <meta name="robots" content="index, follow, noarchive"/>
    <meta name="googlebot" content="noarchive"/>
    <meta name="google-site-verification" content="3fhnNV9w5kMWBAcEUf3o_UTDmExr-47HdkFyjKXdyQ4"/>

    <link rel="home" href="http://glosuj-w-lomiankach.pl"/>
    <link rel="canonical" href="http://glosuj-w-lomiankach.pl{{ request.path }}"/>
    <link rel="author" href="http://www.DialogLomianki.pl"/>
    <link rel="publisher" href="https://plus.google.com/106897195166601500987"/>

    <meta property="og:type" content="article"/>
    <meta property="og:title" content="Głosuj w Łomiankach"/>
    <meta property="og:url" content="http://glosuj-w-lomiankach.pl{{ request.path }}"/>
    <meta property="og:image" content="http://glosuj-w-lomiankach.pl/assets/images/cover.png"/>

    <meta property="og:description" content="Możesz zagłosować w Łomiankach bez meldunku. Wypełnij nasz formularz i dopisz się do rejestru wyborców."/>

    <meta property="og:site_name" content="Głosuj w Łomiankach"/>
    <meta property="fb:admins" content="259770074216711"/>


</head>
<body class="{% block body_class %}{% endblock %}">
{#<script>urls = new bravelabs.limestone.Urls();</script>#}

{% block body %} {% endblock %}

{% assets "js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% block bottom %}{% endblock %}

</body>
</html>

templates/body_.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  {% load compress %}

  <title>{% block title %}{% endblock %}</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">

{% compress css %}
  <link rel="stylesheet" href="{{ STATIC_URL }}css/reset.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/styles.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}smoothness/jquery-ui-1.8.17.custom.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/cleanup.css">
{% endcompress %}

  <link rel="home" href="/" />

    <meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8"/>
    <meta name="author" content="Brave Labs sp. z o.o. - http://www.bravelabs.pl"/>
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="robots" content="index, follow, noarchive"/>
    <meta name="googlebot" content="noarchive"/>
    <meta name="google-site-verification" content=""/>

  <!-- TODO: Create your own custom Modernizr build: www.modernizr.com/download/ -->
  <script src="{{ STATIC_URL }}js/modernizr-2.5.2.min.js"></script>
</head>
<body class="{% block body_class %}{% endblock %}">
{% compress js %}
<script type="text/javascript" src="{{ STATIC_URL }}jquery/jquery-1.7.1.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}jquery/jquery-ui-1.8.17.custom.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}jquery/jquery-ui-i18n.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}jquery/setup.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}jquery/jquery.appear-1.1.1.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/html5boilerplate-logging.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/django-csrf.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/limestone/limestone-more.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/limestone/limestone-bgFade.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/limestone/limestone-editable.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/limestone/limestone-urls.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/crmik/SalesCall.js"></script>
<script>
urls = new bravelabs.limestone.Urls({% urlpatterns %});
</script>
{% endcompress %}
{% block body %} {% endblock %}
</body>
</html>

templates/cookie_info.html
<div id="cookie-info" style="display:none; position:fixed; bottom:0; z-index: 1000; width: 800px; margin-left: -411px; left: 50%; background: #fff; border: 1px solid #909090;  font-size: 12px;">
    <p style="padding: 3px 10px; background: #CCC; color: #000; border-bottom: 1px solid #aaa">
        {% trans %}Informacja o ciasteczkach{% transif %}
        <a class="close-info" style="float: right" href="">Ukryj komunikat</a>
        <a style="margin-right: 1em; float: right" href="/cookies/">Więcej informacji</a>
    </p>
    <div style="padding: 0 10px;">
        <p>
            Pliki cookie pomagają nam udostępniać nasze usługi. Korzystając z tych usług, zgadzasz się na użycie plików cookie.
Więcej informacji
OK
            Tak jak wiele innych serwisów, używamy „ciasteczek” by sprawdzać jak nasza strona jest przez państwo używana (np. liczymy liczbę odwiedzających).
            W swojej przeglądarce, możesz skonfigurować to jak ciasteczka działają.
            Korzystając z serwisu bez zmian konfiguracji swojej przeglądarki wyrażają państwo zgodę na to byśmy mogli dalej korzystać z ciasteczek zapisanych w państwa przeglądarce.
        </p>
    </div>
</div>

templates/footer.html
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-push-8 col-sm-6 col-sm-push-6">
                <a href="http://www.DialogLomianki.pl/Witold-Gawda" title="Witold Gawda" target="_blank">
                    <img class="center-block gawda" title="Witold Gawda" src="{{ url_for("static", filename='images/Witold-Gawda-Kandydat.png') }}">
                </a>
            </div>
            <div class="col-md-4 col-md-pull-0 col-sm-6 col-sm-pull-6">
                <a href="http://www.DialogLomianki.pl/Witold-Gawda" title="Witold Gawda" target="_blank">
                    <img class="center-block plakat" title="Witold Gawda" src="{{ url_for("static", filename='images/Witold-Gawda.png') }}">
                </a>
            </div>
            <div class="col-md-4 col-md-pull-8 col-sm-6">
                <a href="http://www.DialogLomianki.pl/" title="Dialog Łomianki Witold Gawda" target="_blank">
                    <img class="plakat center-block" title="Dialog Łomianki Witold Gawda" src="{{ url_for("static", filename='images/Dialog-Lomianki-Witold-Gawda.png') }}">
                </a>
            </div>
        </div>
        <div class="row" style="margin: 30px 0 10px; color: #454545">
            <div class="col-xs-12">
                <small class="center-block">Sfinansowano ze środków KWW Dialog Zmieni Łomianki. <a href="{{ url_for("glosuj_lokalnie.polityka") }}">Polityka prywatności. Używamy
                    ciasteczek</a></small>
            </div>
        </div>
    </div>
</footer>

templates/header_nav.html
<header>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="background: #fd8c00; color: #FFF">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for("start") }}">Głosuj w Łomiankach</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for("glosuj_lokalnie.Application:create") }}">{% trans %}Wypełnij wniosek{% endtrans %}</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://www.DialogLomianki.pl/Witold-Gawda">{% trans %}Witold Gawda{% endtrans %}</a></li>
                    <li><a href="http://www.DialogLomianki.pl">{% trans %}Dialog Łomianki{% endtrans %}</a></li>
                    {% if security and current_user.is_staff %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans %}Admin{% endtrans %}<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for("auth.User:list") }}"><i class="glyphicon glyphicon-user"></i> {% trans %}Użytkownicy{% endtrans %}</a></li>
                                <li class="divider"></li>
                                <li><a href="{{ url_for("routes") }}"><i class="glyphicon glyphicon-globe"></i> Lista URLi</a></li>
                                <li><a href="{{ url_for("styles") }}"><i class="glyphicon glyphicon-font"></i> Przegląd styli</a></li>
                                <li class="divider"></li>
                                <li><a href="{{ url_for("err") }}"><i class="glyphicon glyphicon-fire"></i> Testowy błąd</a></li>
                            </ul>
                        </li>
                    {% endif %}
                    {% if security and current_user.is_authenticated() %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle nav-avatar" data-toggle="dropdown">
                                {{ current_user.cn }} <img src="{{ current_user.gravatar }}?s=36&d=retro"/>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for("security.logout") }}"><i class="glyphicon glyphicon-off"></i> {% trans %}Logout {% endtrans %}</a></li>
                                <li class="divider"></li>
                                <li><a href="http://gravatar.com"><i class="fa fa-user-md"></i> {% trans %}Change avatar{% endtrans %}</a></li>
                                <li><a href="{{ url_for("auth.profile") }}"><i class="glyphicon glyphicon-user"></i> User account</a></li>
                            </ul>
                        </li>
                    {% else %}
{#
                        <li class=""><a href="{{ url_for("security.login") }}">{% trans %}Log in{% endtrans %}</a></li>
                        <li class=""><a href="{{ url_for("security.register") }}">{% trans %}Register{% endtrans %}</a></li>
#}
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>
</header>

templates/routes.html
{% extends "simple.html" %}
{% block content %}

    <div class="page-header">
        <h1>URL map</h1>
    </div>
    <p class="lead">Lista nazw urli obsługiwanych przez aplikację.</p>

    <table class="table table-striped table-condensed">
        <thead>
        <tr class="head">
            <th class="lp">{% trans %}Lp{% endtrans %}</th>
            <th>{% trans %}Endpoint{% endtrans %}</th>
            <th>{% trans %}Rule{% endtrans %}</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for endpoint, rule in links %}
                <tr class="{{ loop.cycle('', 'even') }}">
                    <td class="lp">{{ loop.index }}</td>
                    <td>{{ endpoint }}</td>
                    <td>{{ rule }}</td>
                </tr>
            {% endfor %}
        </tr>
        </tbody>
    </table>

{% endblock %}

templates/sidebarred.html
{% extends "base.html" %}
{% block body_class %}sidebar{% endblock %}
{% block body %}
<div id="root">
    {% include "header_nav.html" %}
    <div id="alerts-wrap">
        <section id="alerts"></section>
    </div>
    <section id="content">
            <div class="aside-wrap">
                <div class="container">
                <section class="main">
                    <div class="main-inner">
                    {% block main %}{% endblock %}
                    </div>
                </section>
                <aside>
                    {% block sidebar %}{% endblock %}
                </aside>
            </div>
        </div>
    </section>
    <div id="footer-shim"></div>
</div>
{% include "footer.html" %}
{% endblock %}



templates/simple.html
{% extends "base.html" %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/start.html
{% extends "base.html" %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron">
                    <p>&nbsp;</p>

                    <h1>Oddaj głos w Łomiankach</h1>

                    <p>&nbsp;</p>

                    <p>Mieszkasz w Łomiankach, ale nie jesteś tu zameldowany? Chcesz współdecydować o przyszłości swojego miasta? </p>

                    <p>Zarejestruj się w rejestrze wyborców i 16 listopada zagłosuj w wyborach samorządowych w miejscu zamieszkania.</p>

                    <p>&nbsp;</p>

                    <p><a class="btn btn-primary btn-lg" href="{{ url_for("glosuj_lokalnie.Application:create") }}">Wypełnij formularz</a></p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 feature">

                <div class="row">
                    <div class="col-md-3 col-xs-2 text-center dialog-icon">
                        <i class="fa fa-check-square  fa-5x hidden-xs hidden-sm"></i>
                        <i class="fa fa-check-square  fa-3x visible-xs"></i>
                        <i class="fa fa-check-square  fa-4x visible-sm"></i>
                    </div>
                    <div class="col-md-9 col-xs-10">
                        <h1><a href="{{ url_for("glosuj_lokalnie.Application:create") }}">Bez meldunku</a></h1>

                        <p>Nie musisz mieć meldunku w Łomiankach, by tutaj głosować w wyborach. Wystarczy złożenie wniosku o wpisanie do rejestru wyborców</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 feature">
                <div class="row">
                    <div class="col-md-3 col-xs-2 text-center dialog-icon">
                        <i class="fa fa-tasks   fa-5x hidden-xs hidden-sm"></i>
                        <i class="fa fa-tasks   fa-3x visible-xs"></i>
                        <i class="fa fa-tasks   fa-4x visible-sm"></i>
                    </div>
                    <div class="col-md-9 col-xs-10">
                        <h1><a href="{{ url_for("glosuj_lokalnie.Application:create") }}">Wypełnij formularz</a></h1>

                        <p>Przygotowaliśmy dla Ciebie generator formularza, wydrukuj go i złóż osobiście w urzędzie miejskim w Łomiankach</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 feature">
                <div class="row">
                    <div class="col-md-3 col-xs-2 text-center dialog-icon">
                        <i class="fa fa-thumbs-up fa-5x hidden-xs hidden-sm"></i>
                        <i class="fa fa-thumbs-up fa-3x visible-xs"></i>
                        <i class="fa fa-thumbs-up fa-4x visible-sm"></i>
                    </div>
                    <div class="col-md-9 col-xs-10">
                        <h1><a href="{{ url_for("glosuj_lokalnie.Application:create") }}">Decyduj</a></h1>

                        <p>Oddając głos w miejscu zamieszkania, nawet bez meldunku masz wpływ na przyszłość swojej miejscowości.</p>
                    </div>
                </div>
            </div>
            <div class="clearfix visible-lg-block"></div>
        </div>
    </div>
{% endblock %}
RADA JEST ORGANEM

templates/styles.html
{% extends "simple.html" %}
{% block content %}

{% include "typography.html" %}

{% endblock %}